version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: npm run build
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
