version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app  # Mapeia o diretório atual no contêiner para facilitar o desenvolvimento
    ports:
      - "80:80"  # Mapeando a porta 80 do contêiner para a porta 80 do host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
