version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: 
    networks:
      - app-network

  apache:
    image: httpd:alpine
    depends_on:
      - app
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

