version: 1
services:
  - type: web
    name: Front-Respirar
    env: static
    buildCommand: "npm install && npm run build"
    publishPath: "./dist"
    routes:
      - type: rewrite
        source: "/"
        destination: "/index.html"
      - type: rewrite
        source: "/*"
        destination: "/index.html"
