services:
  - type: web
    name: nginx-service
    runtime: node  # Define o ambiente Node.js gerenciado
    buildCommand: "npm run build"
    startCommand: "nginx -g 'daemon off;'"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
