services:
  - type: web
    name: nginx-service
    env: docker
    dockerfilePath: ./Dockerfile  # Verifique se o caminho está correto
    buildCommand: "npm run build"
    startCommand: "nginx -g 'daemon off;'"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
